Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"

  config.vm.provider "hyperv" do |h|
    h.cpus = 2
    h.memory = 2048
    h.vmname = "debian - cobaia"
  end
  
  config.vm.provision "shell", path: "inicializador.sh"

end
