$script = <<-'SCRIPT'
echo "Teste"
sudo dnf install vim -y
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel9"
  config.vm.provider "hyperv" do |h|
    h.cpus = 2
    h.memory = 2048
    h.vmname = "rhel9-lab"
  end
  config.vm.provision :ansible do |ansible| 
    ansible.playbook = "ansible/playbook.yml"
    ansible.verbose = true
  end
end
