Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
      unless File.exist?('./secondDisk.vdi')
        v.customize ['createhd', '--filename', './secondDisk.vdi', '--variant', 'Fixed', '--size', 10 * 1024]
      end
      v.vm.provision :shell, inline: "sudo yum update -y; sudo yum install -y vim"
    end
    config.vm.provision "shell", privileged: false, run: "always", inline: <<-SHELL
    sudo yum update -y
    sudo yum install -y vim
  SHELL
end
