Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.provider "kvm" do |v|
    v.memory = 1024
    v.cpus = 2
  end 
  config.vm.provision :ansible do |ansible| 
    ansible.playbook = "provisioning/playbook.yml"
  end
end